language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
	provider: heroku
	app: fjr-project1-travis
	on: master
	skip_cleanup: true
	api_key:
		secure: Hfcgua1hjWAweDtc+fGsVKOOCvY5LPSEE0kxFosYjiA4l/7zUt5px5kXyvngrhnwBAj6YGUsVbh+Tbr18brHfZJxIza7uZqiBbWpU1tFPuJuwYQ/buyhc288HxsvdaCy0RlNE3aH6p9ybCPzXjWygoUkrRvFuDC3W9AhoDpb+o4EUOhMaa+sgKohsZkzZKfAVTxNhpAVgbvjXid1bGtBe9YBIR8P7iDM+UzeWFC7jPu5VPExL8Tm0XPuvvOA5pebJCy6TEPsxXXFFT6LdD/oLyUYl8Eg9AXhjinofZVFqXb2ixTk4DNvAfH2e5Pf8qGRWAoGQurfWbo8MSQ9zMioFwpjeuCyqXZQo5pLEWqtnam8bXscTOgfptHkYqw9BHLOvvwKCmvkN1YCrI8LLI9gS2dK0etKHbBbTyOpRL18EK/qay+2sH1L/0V/Fayjh7RUE+TZJsylb44Fz7kY2zbF2dOJtjnpEWWRmo+ULf5skzhs2HWYQ2Lpi0E7OJ9/boq4J7/pWIS3dp0Rlrg9ft20ScghWDH6xnPGHteAPmHV58YOy5HPlnjw6tvP6tFKTchnVo/esiDCcjN7bFSWCfdqNF9BTR++HtyJZ+CyB+p1hvez886uq9GojiDJ0HXLElHTLRTmR1Q0O4QbtJIk0Y32A81pE0CJW7Ug4PlXJhmnhvQ=
